services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://dbsonar:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonardb
      - SONAR_JDBC_PASSWORD=sonardb
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    #PW: M2@I2025325656a
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/api/system/status" ]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s

  sonardb:
    image: postgres:17-alpine3.21
    container_name: sonardb
    environment:
      - POSTGRES_USER=sonardb
      - POSTGRES_PASSWORD=sonardb
      - POSTGRES_DB=sonardb
    volumes:
      - db_sonar:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    depends_on:
      sonarqube:
        condition: service_healthy
    environment:
      SONAR_HOST_URL: "http://sonarqube:9000"
      SONAR_LOGIN: VotreKEY
    volumes:
      - ../symfony:/usr/src

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  db_sonar:

#docker-compose run --rm sonar-scanner