services:
  db_coin:
    container_name: pg_coin
    image: postgres:17-alpine3.21
    environment:
      - POSTGRES_USER=m2i
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=db_coin
    volumes:
      - './.db_coin:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    networks:
      - sonarnet

  php_coin:
    container_name: php_coin
    build: ./.docker/php
    working_dir: /www/symfony
    volumes:
      - './symfony:/www/symfony'
    networks:
      - sonarnet

  server_coin:
    container_name: server_coin
    image: nginx:1.27-alpine3.20
    working_dir: /www
    volumes:
      - './symfony:/www/symfony'
      - './.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'
    networks:
      - sonarnet

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonardb:
    container_name: sonardb
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonardb
      - POSTGRES_PASSWORD=sonardb
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: