name: CI

on:
    push:
        branches: ["main"]
jobs:
    build-an-test:
        runs-on: ubuntu-latest

        steps:
            -  name: Checkout Code
               uses: actions/checkout@v4

            - name: build services
              run: docker compose -f docker-compose.yml build

            - name: install dependencies
              run: |
                docker compose run --rm php_coin composer install --no-interaction || \
                docker compose run --rm php_coin composer update --no-interaction

            - name : install sonarqube
              run: |
                docker run --rm -e SONAR_HOST_URL="http://your-sonarqube-server" -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli

            - name: Run SonarQube scan
              run: |
                sonar-scanner -Dsonar.projectKey=my_project_key \
                -Dsonar.host.url=$SONAR_URL \
                -Dsonar.login=$SONAR_TOKEN

            - name: PHP-CS-Fixer
              run: docker compose run --rm php_coin ./vendor/bin/php-cs-fixer fix --dry-run --diff

            - name: PHPStan
              run: |
                docker compose run --rm php_coin ./vendor/bin/phpstan analyse src --level=5

            - name: All tests
              run: |
                  docker compose run --rm php_coin ./vendor/bin/phpunit --testdox

            - name: clean up
              if: always ()
              run: docker compose down