name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build services
        run: docker compose -f docker-compose.yml build

      - name: Install dependencies
        run: |
          docker compose run --rm php_coin composer install --no-interaction || \
          docker compose run --rm php_coin composer update --no-interaction

      - name: Run SonarQube scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          token: ${{ secrets.SONAR_TOKEN }}
          projectKey: 'clement-test'
          projectName: 'clement-test'

      - name: PHP-CS-Fixer
        run: docker compose run --rm php_coin ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: PHPStan
        run: docker compose run --rm php_coin ./vendor/bin/phpstan analyse src --level=5

      - name: All tests
        run: |
          docker compose run --rm php_coin ./vendor/bin/phpunit --testdox

      - name: Clean up
        if: always()
        run: docker compose down
