name: CI

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build services
        run: docker compose -f docker-compose.yml build

      - name: Install dependencies
        run: |
            docker compose run --rm php_coin composer install --no-interaction || \
            docker compose run --rm php_coin composer update --no-interaction

      - name: PHPStan
        run: |
          docker compose run --rm php_coin ./vendor/bin/phpstan analyse src --level=1

#      - name: PHP-CS-Fixer
#        run: docker compose run --rm php_coin ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: All tests
        run: |
          docker compose run --rm php_coin ./vendor/bin/phpunit --testdox

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.0.0"

      - name: Install dependencies
        run: |
          npm init -y
          npm install
          npm ci

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github


      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Permet l'authentification de Semantic Release
        run: npx semantic-release

      - name: Clean up
        if: always()
        run: docker compose down
